# Uncomment the next line to define a global platform for your project
platform :ios, '12.0'

target 'AEPSampleWatchOSApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  #use_frameworks!

  # Pods for AEPSampleWatchOSApp

end

target 'AEPSampleWatchOSApp WatchKit App' do
  # Comment the next line if you don't want to use dynamic frameworks
  #use_frameworks!

  # Pods for AEPSampleWatchOSApp WatchKit App

end

target 'AEPSampleWatchOSApp WatchKit Extension' do
  # Comment the next line if you don't want to use dynamic frameworks
  #use_frameworks!

  # Pods for AEPSampleWatchOSApp WatchKit Extension
    pod 'AEPCore', '~> 3'
    pod 'AEPEdge', '~> 1'
    pod 'AEPUserProfile', '~> 3'
    pod 'AEPAssurance', '~> 3'
    pod 'AEPServices', '~> 3'
    pod 'AEPEdgeConsent', '~> 1'
    pod 'AEPLifecycle', '~>3'
    pod 'AEPMessaging', '~>1'
    pod 'AEPEdgeIdentity', '~>1'
    pod 'AEPSignal', '~>3'

end
